sudo: false
language: java
install: true
jdk:
- openjdk8
script:
  - cd backend-services
  - ./gradlew clean build sonarqube -Dsonar.organization=pipiobjo-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=56be13feec0f3a27ebef137661a4250102d24769 jacocoTestReport