version: "3.3"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  eureka:
    hostname: eureka
    image: com.pipiobjo.microservice/serviceregistry:0.0.1-snapshot
    networks:
      backend:
        ipv4_address: 172.20.0.5
        aliases:
          - eureka
    ports:
          - "8761:8761"
    environment:
        JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Dspring.profiles.active=local"

  webgateway:
      hostname: webgateway
      image: com.pipiobjo.microservice/webgateway:0.0.1-snapshot
      networks:
        backend:
         aliases:
            - webgateway
      ports:
            - "8080:8080"
            - "5005:5005"
      environment:
        JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Dspring.profiles.active=local -Deureka.instance.hostname=webgateway -DeurekaHost=eureka"

  helloWorld:
    hostname: helloworld
    image: com.pipiobjo.microservice/helloworldapp:0.0.1-snapshot
    networks:
      backend:
       aliases:
          - helloworld
    ports:
          - "8180:8080"
          - "5105:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Dspring.profiles.active=local -DeurekaHost=eureka"

  motd:
    hostname: motd
    image: com.pipiobjo.microservice/motdapp:0.0.1-snapshot
    networks:
      backend:
       aliases:
          - motd
    ports:
          - "8280:8080"
          - "5205:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Dspring.profiles.active=local -DeurekaHost=eureka"


