eureka:
  instance:
#    hostname: localhost # should be set from docker env variable
  client:
    registerWithEureka: true
    enabled: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/