eureka:
  instance:
        preferIpAddress: true
#    hostname: localhost # should be set from docker env variable
  client:
    registerWithEureka: true
    enabled: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eurekaHost}:8761/eureka/

logstash.servers: logstash:5000
